name: Sample CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Install Node Environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22

      - name: Install Node Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Files on GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: dist/

  self-hosted-runner:
    runs-on: [self-hosted, cssoft]
    needs: ubuntu-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Download From GitHub Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: ./dist

      - name: Deploy on Nginx Folder
        run: |
          cd dist
          cp -r * /var/www/main
          ls /var/www/main
        
