name: NodeJs Project

on:
  push:
    branches:
      -  main

jobs:
  node-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Node Environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Install Pm2 With npm
        run: |
          sudo apt install npm -y
          npm install -g pm2
          sudo ufw allow 4600
          sudo ufw enable
          sudo ufw reload
          
      - name: Start Service As Dev
        run: |
          npm run build
          pm2 start npm --name "my-node" -- run start
          pm2 status
